--liquibase formatted sql
--changeset filip850:00-create-cars-table

CREATE TABLE cars (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      type VARCHAR(32) NOT NULL,
                      available BOOLEAN NOT NULL
);